// File generated by Antigravity (manually) due to environment issues with FlutterFire CLI.
// To update this file, try running `flutterfire configure` again when node/npm are available.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJyjh08v2FkIa_u0US-n0yYT56Ke3lYo',
    appId: '1:512259810344:web:f38a6a6c0b3c2d1e0f9b8a', // Placeholder ID derived from project number
    messagingSenderId: '512259810344',
    projectId: 'ghumakkad-e2263',
    authDomain: 'ghumakkad-e2263.firebaseapp.com',
    storageBucket: 'ghumakkad-e2263.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGJyjh08v2FkIa_u0US-n0yYT56Ke3lYo',
    appId: '1:512259810344:android:f705a8c3b4fa944d14011d',
    messagingSenderId: '512259810344',
    projectId: 'ghumakkad-e2263',
    storageBucket: 'ghumakkad-e2263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJyjh08v2FkIa_u0US-n0yYT56Ke3lYo',
    appId: '1:512259810344:ios:f705a8c3b4fa944d14011d', // Placeholder matching Android pattern
    messagingSenderId: '512259810344',
    projectId: 'ghumakkad-e2263',
    storageBucket: 'ghumakkad-e2263.firebasestorage.app',
    iosClientId: '512259810344-placeholder.apps.googleusercontent.com',
    iosBundleId: 'in.ghumakkad.app',
  );
}
